version: "3.2"

services:

  first:
    image: andoriasoft/node:latest
    # Local node id: QmRpheLN4JWdAnY7HGJfWFNbfkQCb6tFf4vvA6hgjMZKrR
    command: |
      --name "First node"
      --node-key 0000000000000000000000000000000000000000000000000000000000000001
      --base-path /res/first
      --unsafe-ws-external
      --unsafe-rpc-external
      --rpc-cors "*"
      --port 30333
      --ws-port 9944
      --rpc-port 9933
      --chain=local
      --validator
      --alice
      --rpc-methods=Unsafe
    restart: on-failure
    environment:
      ABCI_RPC_SERVER_URL: 0.0.0.0:26657
      ABCI_SERVER_URL: tcp://first_cosmos:26658
      ABCI_GENESIS_STATE_PATH: /genesis.json
    volumes:
      - ./genesis.json:/genesis.json
    ports:
      - "9933:9933"
      - "9944:9944"
      - "30333:30333"
      - "26657:26657"
    links:
      - first_cosmos

  first_cosmos:
    image: andoriasoft/cosmos-node:latest
    command: start --with-tendermint=false --transport=grpc
    restart: on-failure
    ports:
      - "26658:26658"

  second:
    image: andoriasoft/node:latest
    # Local node id: QmSVnNf9HwVMT1Y4cK1P6aoJcEZjmoTXpjKBmAABLMnZEk
    command: |
      --name "Second node"
      --node-key 0000000000000000000000000000000000000000000000000000000000000002
      --base-path /res/second
      --unsafe-ws-external
      --unsafe-rpc-external
      --rpc-cors "*"
      --chain=local
      --port 30333
      --ws-port 9944
      --rpc-port 9933
      --validator
      --bob
      --rpc-methods=Unsafe
    restart: on-failure
    environment:
      ABCI_SERVER_URL: tcp://second_cosmos:26658
      ABCI_GENESIS_STATE_PATH: /genesis.json
    volumes:
      - ./genesis.json:/genesis.json
    ports:
      - "19933:9933"
      - "19944:9944"
      - "30334:30333"
    links:
      - second_cosmos

  second_cosmos:
    image: andoriasoft/cosmos-node:latest
    command: start --with-tendermint=false --transport=grpc
    restart: on-failure
