version: "3.2"

services:

  nginx:
    image: nginx:1.17.9
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./site:/usr/share/nginx/html
    - ./letsencrypt:/etc/letsencrypt/
    restart: on-failure
    ports:
    - 80:80
    - 443:443
    depends_on:
    - first
    - first_cosmos
    - second
    - second_cosmos

  first:
    image: ghcr.io/adoriasoft/substrate-node:latest
    # Local node id: QmRpheLN4JWdAnY7HGJfWFNbfkQCb6tFf4vvA6hgjMZKrR
    command: |
      --name "First node"
      --node-key 0000000000000000000000000000000000000000000000000000000000000001
      --base-path /res/first
      --unsafe-ws-external
      --unsafe-rpc-external
      --rpc-cors "*"
      --port 30333
      --ws-port 9944
      --rpc-port 9933
      --chain=local
      --validator
      --alice
      --rpc-methods=Unsafe
    restart: on-failure
    environment:
      ABCI_RPC_SERVER_URL: 0.0.0.0:26657
      ABCI_SERVER_URL: tcp://first_cosmos:26658
      ABCI_GENESIS_STATE_PATH: /genesis.json
    volumes:
      - ./res:/res
      - ./genesis.json:/genesis.json
    ports:
      - "9933:9933"
      - "9944:9944"
      - "30333:30333"
      - "26657:26657"
    links:
      - first_cosmos

  first_cosmos:
    image: ghcr.io/adoriasoft/cosmos-node:latest
    command: nsd start --with-tendermint=false --transport=grpc
    restart: on-failure
    ports:
      - "26658:26658"

  second:
    image: ghcr.io/adoriasoft/substrate-node:latest
    # Local node id: QmSVnNf9HwVMT1Y4cK1P6aoJcEZjmoTXpjKBmAABLMnZEk
    command: |
      --name "Second node"
      --node-key 0000000000000000000000000000000000000000000000000000000000000002
      --base-path /res/second
      --unsafe-ws-external
      --unsafe-rpc-external
      --rpc-cors "*"
      --port 30333
      --ws-port 9944
      --rpc-port 9933
      --chain=local
      --validator
      --bob
      --rpc-methods=Unsafe
    restart: on-failure
    environment:
      ABCI_RPC_SERVER_URL: 0.0.0.0:26657
      ABCI_SERVER_URL: tcp://second_cosmos:26658
      ABCI_GENESIS_STATE_PATH: /genesis.json
    volumes:
      - ./res:/res
      - ./genesis.json:/genesis.json
    ports:
      - "19933:9933"
      - "19944:9944"
      - "30334:30333"
      - "36657:36657"
    links:
      - second_cosmos

  second_cosmos:
    image: ghcr.io/adoriasoft/cosmos-node:latest
    command: nsd start --with-tendermint=false --transport=grpc
    restart: on-failure
    ports:
      - "36658:26658"
