version: "3.2"
services:
  dev_substrate:
    image: ghcr.io/adoriasoft/substrate-node:latest
    command: --dev
    environment:
      ABCI_RPC_SERVER_URL: 0.0.0.0:26657
      ABCI_SERVER_URL: tcp://dev_cosmos:26658
      ABCI_GENESIS_STATE_PATH: /genesis.json
    volumes:
      - ./.maintain/genesis.json:/genesis.json
    ports:
      - "9944:9944"
      - "26657:26657"
    links:
      - dev_cosmos

  dev_cosmos:
    image: ghcr.io/adoriasoft/cosmos-node:latest
    command: nsd start --with-tendermint=false --transport=grpc
    restart: on-failure
    ports:
      - "26658:26658"
