version: "3.2"
services:
  dev:
    image: andoriasoft/node
    command: |
      --dev
      --unsafe-ws-external
    environment:
      ABCI_SERVER_URL: http://cosmos:8082/abci/v1/
    ports:
      - "9933:9933"
      - "9944:9944"
      - "30333:30333"
    links:
      - cosmos

  cosmos:
    image: andoriasoft/cosmos-node:latest
