version: "3.2"
services:
  dev:
    container_name: node-template
    image: parity/rust-builder:latest
    working_dir: /var/www/node-template
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/node-template/.cargo
      - ABCI_APP_STATE=${ABCI_APP_STATE}
    volumes:
      - .:/var/www/node-template
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/node-template --dev --ws-external"
