name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linux:
    runs-on: ubuntu-18.04
    
    steps:
      - uses: actions/checkout@v1
      - name: setup
        run: | 
            curl https://getsubstrate.io -sSf | bash -s -- --fast
            source ~/.cargo/env
            rustup default stable
            rustup update nightly
            rustup update stable
            rustup target add wasm32-unknown-unknown --toolchain nightly
            rustup update
      - name: build
        run: | 
            cargo clean
            cargo build --release
      - name: test
        run: | 
            cargo test --all
