name: CI

on: [push, pull_request]

jobs:
  build_and_test_substrate:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: rust-setup
        run: |
          rustup default nightly
          rustup target add wasm32-unknown-unknown
          rustup component add rustfmt
          rustup update
      - name: test
        run: cargo test --all

  integration_tests:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15' # The Go version to download (if necessary) and use.
      - name: rust-setup
        run: |
          rustup default nightly
          rustup target add wasm32-unknown-unknown
          rustup component add rustfmt
          rustup update
      - name: build-cosmos
        run: |
          git clone https://github.com/cosmos/cosmos-sdk.git
          cd cosmos-sdk
          git checkout v0.42.3
          make build
          cp build/simd ~/go/bin
          cd ..
          ./scripts/cosmos-init.sh
      - name: build_substrate
        run: cargo build
      - name: run_tests
        run: |
          cd scripts/integration_tests
          ./basic_test.sh
          ./basic_test_2_nodes.sh
          ./broadcast_tx.sh
          ./stoping_nodes_test.sh
          ./tx_spamming_test.sh


  clean:
    name: Check code format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2020-08-19
          components: rustfmt, clippy
          override: true
      - name: Install target
        run: rustup target add wasm32-unknown-unknown
      - name: Check the format
        run: cargo +nightly-2020-08-19 fmt --all -- --check
      - name: Run clippy
        run: cargo +nightly-2020-08-19 clippy -- -D warnings -A clippy::large-enum-variant -A clippy::too-many-arguments -A clippy::unnecessary-mut-passed -A clippy::type-complexity
