name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build_and_test_substrate:
    runs-on: ubuntu-18.04
    
    steps:
      - uses: actions/checkout@v1
      - name: rust-setup
        run: | 
            curl https://getsubstrate.io -sSf | bash -s -- --fast
            source ~/.cargo/env
            rustup default nightly
            rustup target add wasm32-unknown-unknown
            rustup component add rustfmt
            rustup update
      - name: dependecies-setup
        run: |
            export PATH="$HOME/go/bin:$PATH"
            git submodule update --init
            cd cosmos-sdk
            git checkout feature/add_nameservice
            make build-simd
            cd simapp
            rm -rf ~/.nsd
            rm -rf ~/.nscli
            nsd init test --chain-id=namechain
            sudo nscli --chain-id namechain --output json keys add jack
            nscli --chain-id namechain --output json keys add alice
            nsd add-genesis-account $(nscli keys show jack -a) 1000nametoken,100000000stake
            nsd add-genesis-account $(nscli keys show alice -a) 1000nametoken,100000000stakes
            nsd gentx jack --chain-id namechain
            echo "Collecting genesis txs..."
            nsd collect-gentxs
            echo "Validating genesis file..."
            nsd validate-genesis
      - name: build
        run: cargo build
      - name: test
        run: cargo test --all
      - name: integration-test
        run: |
            export PATH="$HOME/go/bin:$PATH"
            cd scripts/integration_tests/
          #  ./basic_test.sh

