name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build_and_test_substrate:
    runs-on: ubuntu-18.04
    
    steps:
      - uses: actions/checkout@v1
      - name: rust-setup
        run: | 
            rustup default nightly
            rustup target add wasm32-unknown-unknown
            rustup component add rustfmt
            rustup update
      - name: build
        run: cargo build
      - name: test
        run: cargo test --all

  clean:
    name: Check code format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2020-08-19
          components: rustfmt, clippy
          override: true
      - name: Install target
        run: rustup target add wasm32-unknown-unknown
      - name: Check the format
        run: cargo +nightly-2020-08-19 fmt --all -- --check
      - name: Run clippy
        run: cargo +nightly-2020-08-19 clippy --all-targets --all-features -- -D warnings
