name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linux:
    runs-on: ubuntu-18.04
    
    steps:
      - uses: actions/checkout@v1
      - name: setup
        run: curl https://getsubstrate.io -sSf | bash -s -- --fast
      - name: build
        run: cargo build --release
        
  macos:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: setup
        run: curl https://getsubstrate.io -sSf | bash -s -- --fast
      - name: build
        run: cargo build --release