name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linux:
    runs-on: ubuntu-18.04
    
    steps:
      - uses: actions/checkout@v1
      - name: setup
        run: sudo apt install -y cmake pkg-config libssl-dev git gcc build-essential clang libclang-dev
      - name: build
        run: cargo build --release