name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linux:
    runs-on: ubuntu-18.04
    
    steps:
      - uses: actions/checkout@v1
      - name: setup1
        run: sudo apt install -y cmake pkg-config libssl-dev git gcc build-essential clang libclang-dev
      - name: install_rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
      - name: setup_env
        run: source $HOME/.cargo/env
      - name: build
        run: cargo build --release
        
