name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linux:
    runs-on: ubuntu-18.04
    
    steps:
      - uses: actions/checkout@v1
      - name: setup
        run: | 
            sudo apt update
            sudo apt-get update
      - name: dependecies
        run: |
            sudo apt-get install -y cmake pkg-config libssl-dev git gcc build-essential clang libclang-dev
            curl https://sh.rustup.rs -sSf | sh
            rustup default stable
            rustup update nightly
            rustup target add wasm32-unknown-unknown --toolchain nightly
            rustup update
      - name: build
        run: cargo build --release
      - name: test
        run: cargo test --all