[package]
name = "json-rpc-server"
version = "0.1.0"
authors = ["Mr-Leshiy <leshiy12345678@gmail.com>"]
edition = "2018"

[dependencies]
jsonrpc-http-server = { git = "https://github.com/enfipy/jsonrpc", rev = "4bca2c5186a873488d5fb989b28cb9c7225ec9c6" }
